# Generated by Django 5.0.6 on 2024-05-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('mod', models.CharField(max_length=50, verbose_name='модель')),
                ('released_at', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_level', models.CharField(choices=[('0', 'Производитель'), ('1', 'Поставщик'), ('2', 'Продавец')], default='0', max_length=1, verbose_name='Уровень в иерархии')),
                ('trader_type', models.CharField(choices=[('factory', 'Завод'), ('retail', 'Розничная сеть'), ('individual', 'Индивидуальный предприниматель')], default='factory', max_length=20, verbose_name='Тип звена')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house', models.CharField(max_length=50, verbose_name='Дом(номер, литера, помещение)')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления в систему')),
                ('products', models.ManyToManyField(to='retail.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.trader', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Звено торговой сети',
                'verbose_name_plural': 'Звенья торговой сети',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory', to='retail.trader', verbose_name='Производитель')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider', to='retail.trader', verbose_name='Поставщик')),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade', to='retail.trader', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Торговая сеть',
                'verbose_name_plural': 'Торговые сети',
            },
        ),
    ]
